services:
  telegram-gateway:
    build:
      context: ../../app/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ../../app/public/:/app/public
      - ../../app/.tmp/:/app/.tmp
    ports:
      - "1337:1337"
    env_file:
      - ./.env
